//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBF_MoreComplicatedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirement()
        {
            this.TestMaps = new HashSet<TestMap>();
        }
    
        public int Record_Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TestMethod { get; set; }
        public bool IsNumeric { get; set; }
        public decimal MinimumInternal { get; set; }
        public decimal MaximumInternal { get; set; }
        public decimal MinimumExternal { get; set; }
        public decimal MaximumExternal { get; set; }
        public bool IsPassFail { get; set; }
        public bool IsString { get; set; }
        public bool IsPressTest { get; set; }
        public bool IsLamTest { get; set; }
        public bool IsSlitterTest { get; set; }
        public bool IsActive { get; set; }
        public bool QuarantineIfFail { get; set; }
        public int SequenceNumber { get; set; }
        public bool IncludeCOA { get; set; }
        public int MasterItemID { get; set; }
        public string Selector { get; set; }
        public string COCDisplayMethod { get; set; }
        public string COCDisplaySpec { get; set; }
        public string COCDisplayUnitOfMeasure { get; set; }
        public string COCDisplayVariance { get; set; }
        public string TextIfPass { get; set; }
        public string TextIfFail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestMap> TestMaps { get; set; }
    }
}
