//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBF_MoreComplicatedModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestMap
    {
        public int Record_Number { get; set; }
        public int Test_Number { get; set; }
        public int Requirement_Number { get; set; }
    
        public virtual Requirement Requirement { get; set; }
        public virtual Test Test { get; set; }
    }
}
