// <auto-generated />
namespace FluentApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SetCourseLevelToEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SetCourseLevelToEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201804250437160_SetCourseLevelToEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
