//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Address()
        {
            this.QALabTests = new HashSet<QALabTest>();
        }
    
        public int Record_Number { get; set; }
        public string Company { get; set; }
        public string Address1 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string zip { get; set; }
        public string Country { get; set; }
        public string Contact { get; set; }
        public string Job_Title { get; set; }
        public Nullable<int> Type_Code { get; set; }
        public string Class { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string EMail { get; set; }
        public string URL { get; set; }
        public Nullable<bool> Credit { get; set; }
        public Nullable<decimal> Max_Credit { get; set; }
        public Nullable<decimal> Default_Freight { get; set; }
        public Nullable<decimal> Max_PO { get; set; }
        public Nullable<int> Freight_Code { get; set; }
        public Nullable<int> Terms_Code { get; set; }
        public bool Quote_Alert { get; set; }
        public Nullable<bool> PO_Alert { get; set; }
        public string PO_Alert_Text { get; set; }
        public string Account_Number { get; set; }
        public string Quote_Alert_Text { get; set; }
        public string Price_Alert_Text { get; set; }
        public string General_Text { get; set; }
        public string PO_Text { get; set; }
        public Nullable<bool> WO_Hold { get; set; }
        public string WO_Hold_Text { get; set; }
        public string Summary { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<System.DateTime> Last_Price_Increase { get; set; }
        public Nullable<System.DateTime> Last_modified { get; set; }
        public Nullable<int> Modified_By { get; set; }
        public bool Send_Calendar { get; set; }
        public Nullable<int> Mold_Code { get; set; }
        public Nullable<bool> Imported { get; set; }
        public string Import_Class { get; set; }
        public bool Show_PP_Logo_on_Labels { get; set; }
        public Nullable<int> Default_Quote_Contact { get; set; }
        public Nullable<int> Default_Order_Contact { get; set; }
        public Nullable<int> Default_Billing_Contact { get; set; }
        public Nullable<int> Default_Problem_Contact { get; set; }
        public string Required_PO_Attachement { get; set; }
        public bool Include_Roll_Price { get; set; }
        public bool Include_MSI_Price { get; set; }
        public Nullable<int> Salesperson_Code { get; set; }
        public Nullable<int> Broker_Code { get; set; }
        public bool Include_Per_Pound_Price { get; set; }
        public Nullable<int> Default_Overrun_Surface { get; set; }
        public Nullable<int> Default_Overrun_Reverse { get; set; }
        public Nullable<int> Default_Overrun_Seasonal { get; set; }
        public Nullable<int> CSR_Code { get; set; }
        public Nullable<int> Grace_Period_Days { get; set; }
        public Nullable<int> Grace_Limit { get; set; }
        public Nullable<int> Pre_Approve_Purchases_By { get; set; }
        public Nullable<bool> Must_Weigh_Each_Printed_Roll { get; set; }
        public Nullable<bool> Customer_Required_Printed_Packing_List { get; set; }
        public Nullable<bool> Invoice_Customer_When_BOL_Created { get; set; }
        public string Ship_To { get; set; }
        public string Ship_Address_1 { get; set; }
        public string Ship_Address_2 { get; set; }
        public string Ship_City { get; set; }
        public string Ship_State { get; set; }
        public string Ship_Zip { get; set; }
        public Nullable<bool> Vendor_Supplies_Barcodes { get; set; }
        public string Bill_To_Name { get; set; }
        public string Default_Roll_Specifier_Code { get; set; }
        public Nullable<decimal> Default_Roll_Size { get; set; }
        public Nullable<bool> Customer_Requires_Certificate_of_Analysis { get; set; }
        public string Default_PO_Note { get; set; }
        public Nullable<bool> Show_On_Order_Planning { get; set; }
        public bool Customer_Requires_New_Item_Labels { get; set; }
        public Nullable<bool> Show_Alert_On_BOL { get; set; }
        public string Alert_Text_For_New_BOL { get; set; }
        public Nullable<bool> Print_Customer_Labels_When_Slitting { get; set; }
        public Nullable<bool> Accepts_Docusign { get; set; }
        public bool Include_Impression_Price { get; set; }
        public bool Include_1kImpression_Price { get; set; }
        public bool PendingApproval { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> Receipt_For_Invoice_Mails { get; set; }
        public Nullable<bool> Send_Calendar_Include_In_Current_Mailing { get; set; }
        public Nullable<bool> Require_PP_Job_Number_On_Purchase_Orders { get; set; }
        public string Notification_EMail { get; set; }
        public Nullable<int> Art_Invoice_Terms_code { get; set; }
        public Nullable<int> CSR_Backup_Code { get; set; }
        public Nullable<bool> Send_Correct_Action_Reports { get; set; }
        public Nullable<bool> Allow_Schedule_Even_If_Over_Credit_Limit { get; set; }
        public Nullable<bool> Allow_Schedule_Even_If_Have_Pending_Art_Invoices { get; set; }
        public Nullable<bool> Do_Not_Ship_Hold { get; set; }
        public Nullable<bool> Customer_Requires_Certificate_of_Compliance { get; set; }
        public Nullable<int> Number_Of_Pallet_Labels_On_Slitter { get; set; }
        public Nullable<bool> Ship_Collect { get; set; }
        public Nullable<int> Supplier_Type_Number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QALabTest> QALabTests { get; set; }
    }
}
