//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class polyprintEntities : DbContext
    {
        public polyprintEntities()
            : base("name=polyprintEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<QALabRequirement> QALabRequirements { get; set; }
        public virtual DbSet<QALabResultItem> QALabResultItems { get; set; }
        public virtual DbSet<QALabTestMap> QALabTestMaps { get; set; }
        public virtual DbSet<QALabTest> QALabTests { get; set; }
    }
}
