//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class polyprintEntities : DbContext
    {
        private static string serverName = "PP-MUSTANG";
        private static string format = "metadata=res://*/Model.csdl|res://*/Model.ssdl|res://*/Model.msl;provider=System.Data.SqlClient;provider connection string=\"{0}\"";
        private static string connectionString = $"data source={serverName};initial catalog=polyprint;persist security info=True;user id=sa;password=MngDBsvr2008@polyprint;MultipleActiveResultSets=True;App=EntityFramework";

        public polyprintEntities() : base(String.Format(format, connectionString)) { }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<QALabRequirement> QALabRequirements { get; set; }
        public virtual DbSet<QALabResultItem> QALabResultItems { get; set; }
        public virtual DbSet<QALabTestMap> QALabTestMaps { get; set; }
        public virtual DbSet<QALabTest> QALabTests { get; set; }

        
    }
}
