//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class QALabRequirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QALabRequirement()
        {
            this.QALabResultItems = new HashSet<QALabResultItem>();
            this.QALabTestMaps = new HashSet<QALabTestMap>();
        }
    
        public int Record_Number { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TestMethod { get; set; }
        public bool Is_Numeric { get; set; }
        public Nullable<decimal> MinimumInternal { get; set; }
        public Nullable<decimal> MaximumInternal { get; set; }
        public Nullable<decimal> MinimumExternal { get; set; }
        public Nullable<decimal> MaximumExternal { get; set; }
        public bool Is_PassFail { get; set; }
        public bool Is_String { get; set; }
        public bool Is_Press_Test { get; set; }
        public bool Is_Laminator_Test { get; set; }
        public bool Is_Slitter_Test { get; set; }
        public bool Is_Active { get; set; }
        public Nullable<bool> Quarantine_If_Fail { get; set; }
        public Nullable<int> Sequence_Number { get; set; }
        public Nullable<bool> Include_In_COA { get; set; }
        public Nullable<int> Master_Item_Id { get; set; }
        public string Selector { get; set; }
        public string COC_Display_Method { get; set; }
        public string COC_Display_Spec { get; set; }
        public string COC_Display_Unit_Of_Measure { get; set; }
        public string COC_Display_Variance { get; set; }
        public string Text_If_Pass { get; set; }
        public string Text_If_Fail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QALabResultItem> QALabResultItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QALabTestMap> QALabTestMaps { get; set; }
    }
}
